export const ALL_ENTRY_REQUEST = "ALL_ENTRY_REQUEST";
export const ALL_ENTRY_SUCCESS = "ALL_ENTRY_SUCCESS";
export const ALL_ENTRY_FAIl = "ALL_ENTRY_FAIL";

export const SINGLE_ENTRY_REQUEST = "SINGLE_ENTRY_REQUEST";
export const SINGLE_ENTRY_SUCCESS = "SINGLE_ENTRY_SUCCESS";
export const SINGLE_ENTRY_FAIl = "SINGLE_ENTRY_FAIL";

export const CREATE_ENTRY_REQUEST = "CREATE_ENTRY_REQUEST";
export const CREATE_ENTRY_SUCCESS = "CREATE_ENTRY_SUCCESS";
export const CREATE_ENTRY_RESET = "CREATE_ENTRY_RESET";
export const CREATE_ENTRY_FAIl = "CREATE_ENTRY_FAIL";

export const DELETE_ENTRY_REQUEST = "DELETE_ENTRY_REQUEST";
export const DELETE_ENTRY_SUCCESS = "DELETE_ENTRY_SUCCESS";
export const DELETE_ENTRY_RESET = "DELETE_ENTRY_RESET";
export const DELETE_ENTRY_FAIl = "DELETE_ENTRY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
